const config = {
    "team_ids": {
        "new jersey devils": 1,
        "new york islanders": 2,
        "new york rangers": 3,
        "philadelphia flyers": 4,
        "pittsburgh penguins": 5,
        "boston bruins": 6,
        "buffalo sabres": 7,
        "montreal canadiens": 8,
        "ottawa senators": 9,
        "toronto maple leafs": 10,
        "carolina hurricanes": 12,
        "florida panthers": 13,
        "tampa bay lightning": 14,
        "washington capitals": 15,
        "chicago blackhawks": 16,
        "detroit red wings": 17,
        "nashville predators": 18,
        "st. louis blues": 19,
        "calgary flames": 20,
        "colorado avalanche": 21,
        "edmonton oilers": 22,
        "vancouver canucks": 23,
        "anaheim ducks": 24,
        "dallas stars": 25,
        "los angeles kings": 26,
        "san jose sharks": 28,
        "columbus blue jackets": 29,
        "minnesota wild": 30,
        "winnipeg jets": 52,
        "arizona coyotes": 53,
        "vegas golden knights": 54
    },
    "team_abbrs": {
        "new jersey devils": "njd",
        "new york islanders": "nyi",
        "new york rangers": "nyr",
        "philadelphia flyers": "phi",
        "pittsburgh penguins": "pit",
        "boston bruins": "bos",
        "buffalo sabres": "buf",
        "montreal canadiens": "mon",
        "montréal canadiens": "mon",
        "ottawa senators": "ott",
        "toronto maple leafs": "tor",
        "carolina hurricanes": "car",
        "florida panthers": "fla",
        "tampa bay lightning": "tam",
        "washington capitals": "wsh",
        "chicago blackhawks": "chi",
        "detroit red wings": "det",
        "nashville predators": "nas",
        "st. louis blues": "stl",
        "calgary flames": "cal",
        "colorado avalanche": "col",
        "edmonton oilers": "edm",
        "vancouver canucks": "van",
        "anaheim ducks": "ana",
        "dallas stars": "dal",
        "los angeles kings": "lak",
        "san jose sharks": "sjs",
        "columbus blue jackets": "cbj",
        "minnesota wild": "min",
        "winnipeg jets": "win",
        "arizona coyotes": "ari",
        "vegas golden knights": "vgk",
        "team atlantic": "atl",
        "atlantic": "atl",
        "team metropolitan": "met",
        "metropolitan": "met",
        "team central": "cen",
        "central": "cen",
        "team pacific": "pac",
        "pacific": "pac",
        "team alfredsson": "red",
        "team chara": "blu",
        "team foligno": "blk",
        "team toews": "wht",
        "team staal": "asr",
        "team lidstrom": "asb",
        "all-stars east": "ase",
        "all-stars west": "asw",
        "young stars east": "yse",
        "young stars west": "ysw",
        "american all-stars": "awa",
        "canadian all-stars": "cwa"
    },
    "divisions": {
        "new jersey devils": "metropolitan",
        "new york islanders": "metropolitan",
        "new york rangers": "metropolitan",
        "philadelphia flyers": "metropolitan",
        "pittsburgh penguins": "metropolitan",
        "columbus blue jackets": "metropolitan",
        "washington capitals": "metropolitan",
        "carolina hurricanes": "metropolitan",
        "boston bruins": "atlantic",
        "buffalo sabres": "atlantic",
        "montreal canadiens": "atlantic",
        "montréal canadiens": "atlantic",
        "ottawa senators": "atlantic",
        "toronto maple leafs": "atlantic",
        "florida panthers": "atlantic",
        "tampa bay lightning": "atlantic",
        "detroit red wings": "atlantic",
        "chicago blackhawks": "central",
        "nashville predators": "central",
        "st. louis blues": "central",
        "colorado avalanche": "central",
        "dallas stars": "central",
        "minnesota wild": "central",
        "winnipeg jets": "central",
        "edmonton oilers": "pacific",
        "vancouver canucks": "pacific",
        "calgary flames": "pacific",
        "anaheim ducks": "pacific",
        "los angeles kings": "pacific",
        "san jose sharks": "pacific",
        "arizona coyotes": "pacific",
        "vegas golden knights": "pacific",
        "all-stars east": "all-star",
        "all-stars west": "all-star",
        "young stars east": "all-star",
        "young stars west": "all-star",
        "american all-stars": "all-star",
        "canadian all-stars":"all-star",
        "team atlantic": "all-star",
        "team metropolitan": "all-star",
        "team central": "all-star",
        "team pacific": "all-star"
    },
    "conferences": {
        "new jersey devils": "eastern",
        "new york islanders": "eastern",
        "new york rangers": "eastern",
        "philadelphia flyers": "eastern",
        "pittsburgh penguins": "eastern",
        "columbus blue jackets": "eastern",
        "washington capitals": "eastern",
        "carolina hurricanes": "eastern",
        "boston bruins": "eastern",
        "buffalo sabres": "eastern",
        "montreal canadiens": "eastern",
        "montréal canadiens": "eastern",
        "ottawa senators": "eastern",
        "toronto maple leafs": "eastern",
        "florida panthers": "eastern",
        "tampa bay lightning": "eastern",
        "detroit red wings": "eastern",
        "chicago blackhawks": "western",
        "nashville predators": "western",
        "st. louis blues": "western",
        "colorado avalanche": "western",
        "dallas stars": "western",
        "minnesota wild": "western",
        "winnipeg jets": "western",
        "edmonton oilers": "western",
        "vancouver canucks": "western",
        "calgary flames": "western",
        "anaheim ducks": "western",
        "los angeles kings": "western",
        "san jose sharks": "western",
        "arizona coyotes": "western",
        "vegas golden knights": "western",
        "all-stars east": "all-star",
        "all-stars west": "all-star",
        "young stars east": "all-star",
        "young stars west": "all-star",
        "american all-stars": "all-star",
        "canadian all-stars":"all-star",
        "team atlantic": "all-star",
        "team metropolitan": "all-star",
        "team central": "all-star",
        "team pacific": "all-star"
    },
    "eastern": {
        "atlantic": {
            "bos": {
                "name": "Boston Bruins",
                "home": "Boston",
                "conference": "eastern",
                "division": "atlantic",
                "abbreviation": "bos",
                "mascot": "Bruins",
                "color1": "#FFB81C",
                "color2": "#000000",
                "color3": "",
                "id": 6
            },
            "buf": {
                "name": "Buffalo Sabres",
                "home": "Buffalo",
                "conference": "eastern",
                "division": "Atlantic",
                "abbreviation": "buf",
                "mascot": "Sabres",
                "color1": "#002654",
                "color2": "#FCB514",
                "color3": "#ADAFAA",
                "id": 2
            },
            "fla": {
                "name": "Florida Panthers",
                "home": "Florida",
                "conference": "eastern",
                "division": "atlantic",
                "abbreviation": "fla",
                "mascot": "Panthers",
                "color1": "#041E42",
                "color2": "#C8102E",
                "color3": "#B9975B",
                "id": 3
            },
            "tor": {
                "name": "Toronto Maple Leafs",
                "home": "Toronto",
                "conference": "eastern",
                "division": "atlantic",
                "abbreviation": "tor",
                "mascot": "Maple Leafs",
                "color1": "#00205B",
                "color2": "#00205B",
                "color3": "#FFFFFF",
                "id": 4
            },
            "mon": {
                "name": "Montreal Canadiens",
                "home": "Montreal",
                "conference": "eastern",
                "division": "atlantic",
                "abbreviation": "mon",
                "mascot": "Canadiens",
                "color1": "#AF1E2D",
                "color2": "#192168",
                "id": 5
            },
            "tam": {
                "name": "Tampa Bay Lightning",
                "home": "Tampa Bay",
                "conference": "eastern",
                "division": "atlantic",
                "abbreviation": "tam",
                "mascot": "Lightning",
                "color1": "#002868",
                "color2": "#002868",
                "id": 1
            },
            "ott": {
                "name": "Ottawa Senators",
                "home": "Ottawa",
                "conference": "eastern",
                "division": "atlantic",
                "abbreviation": "ott",
                "mascot": "Senators",
                "color1": "#C52032",
                "color2": "#C2912C",
                "color3": "#000000",
                "id": 7
            },
            "det": {
                "name": "Detroit Red Wings",
                "home": "Detroit",
                "conference": "eastern",
                "division": "atlantic",
                "abbreviation": "det",
                "mascot": "Red Wings",
                "color1": "#CE1126",
                "color2": "#CE1126",
                "color3": "#000000",
                "id": 8
            }
        },
        "metropolitan": {
            "nyr": {
                "name": "New York Rangers",
                "home": "New York",
                "conference": "eastern",
                "division": "metropolitan",
                "abbreviation": "nyr",
                "mascot": "Rangers",
                "color1": "#0038A8",
                "color2": "#CE1126",
                "color3": "#FFFFFF",
                "id": 9
            },
            "nyi": {
                "name": "New York Islanders",
                "home": "New York",
                "conference": "eastern",
                "division": "metropolitan",
                "abbreviation": "nyi",
                "mascot": "Islanders",
                "color1": "#00539B",
                "color2": "#F47D30",
                "color3": "",
                "id": 10
            },
            "pit": {
                "name": "Pittsburg Penguins",
                "home": "Pittsburg",
                "conference": "eastern",
                "division": "metropolitan",
                "abbreviation": "pit",
                "mascot": "Penguins",
                "color1": "#000000",
                "color2": "#FCB514",
                "color3": "#CFC493",
                "color4": "#FFFFFF",
                "id": 11
            },
            "car": {
                "name": "Carolina Hurricanes",
                "home": "Carolina",
                "conference": "eastern",
                "division": "metropolitan",
                "abbreviation": "car",
                "mascot": "Hurricanes",
                "color1": "#CC0000",
                "color2": "#000000",
                "color3": "#A2AAAD",
                "id": 12
            },
            "wsh": {
                "name": "Washington Capitals",
                "home": "Washington",
                "conference": "eastern",
                "division": "metropolitan",
                "abbreviation": "wsh",
                "mascot": "Capitals",
                "color1": "#041E42",
                "color2": "#C8102E",
                "color3": "FFFFFF",
                "id": 13
            },
            "phi": {
                "name": "Philadelphia Flyers",
                "home": "Philadelphia",
                "conference": "eastern",
                "division": "metropolitan",
                "abbreviation": "phi",
                "mascot": "Flyers",
                "color1": "#F74902",
                "color2": "#000000",
                "color3": "FFFFFF",
                "id": 14
            },
            "cbj": {
                "name": "Colombus Blue Jackets",
                "home": "Colombus",
                "conference": "eastern",
                "division": "metropoloitan",
                "abbreviation": "cbj",
                "mascot": "Blue Jackets",
                "color1": "#002654",
                "color2": "#CE1126",
                "color3": "#A4A9AD",
                "id": 15
            },
            "njd": {
                "name": "New Jersey Devils",
                "home": "New Jersey",
                "conference": "eastern",
                "division": "metropolitan",
                "abbreviation": "njd",
                "mascot": "Devils",
                "color1": "#CE1126",
                "color2": "#000000",
                "color3": "FFFFFF",
                "id": 16
            }
        }
    },
    "western": {
        "central": {
            "dal": {
                "name": "Dallas Stars",
                "home": "Dallas",
                "conference": "western",
                "division": "central",
                "abbreviation": "dal",
                "mascot": "Stars",
                "color1": "#006847",
                "color2": "#8F8F8C",
                "color3": "#111111",
                "id": 17
            },
            "chi": {
                "name": "Chicago Blackhawks",
                "home": "Chicago",
                "conference": "western",
                "division": "central",
                "abbreviation": "chi",
                "mascot": "Blackhawks",
                "color1": "#CF0A2C",
                "color2": "#000000",
                "color3": "#FF671B",
                "color4": "#00833E",
                "color5": "#FFD100",
                "id": 18
            },
            "min": {
                "name": "Minnesota Wild",
                "home": "Minnesota",
                "conference": "western",
                "division": "central",
                "abbreviation": "min",
                "mascot": "Wild",
                "color1": "#A6192E",
                "color2": "#154734",
                "color3": "#EAAA00",
                "color4": "#DDCBA4",
                "id": 19
            },
            "win": {
                "name": "Winnipeg Jets",
                "home": "Winnipeg",
                "conference": "western",
                "division": "central",
                "abbreviation": "win",
                "mascot": "Jets",
                "color1": "#041E42",
                "color2": "#004C97",
                "color3": "#AC162C",
                "color4": "#7B303E",
                "color5": "#55565A",
                "color6": "#8E9090",
                "color7": "#FFFFFF",
                "id": 20
            },
            "stl": {
                "name": "St. Louis Blues",
                "home": "St. Louis",
                "conference": "western",
                "division": "central",
                "abbreviation": "stl",
                "mascot": "Blues",
                "color1": "#002F87",
                "color2": "#FCB514",
                "color3": "#041E42",
                "color4": "#FFFFFF",
                "id": 21
            },
            "nas": {
                "name": "Nashville Predators",
                "home": "Nashville",
                "conference": "western",
                "division": "central",
                "abbreviation": "nas",
                "mascot": "Predators",
                "color1": "#FFB81C",
                "color2": "#041E42",
                "color3": "#FFFFFF",
                "id": 22
            },
            "col": {
                "name": "Colorado Avalanche",
                "home": "Colorado",
                "conference": "western",
                "division": "central",
                "abbreviation": "col",
                "mascot": "Avalanche",
                "color1": "#6F263D",
                "color2": "#236192",
                "color3": "#A2AAAD",
                "color4": "#000000",
                "id": 23
            }
        },
        "pacific": {
            "lak": {
                "name": "Los Angeles",
                "home": "Kings",
                "conference": "western",
                "division": "pacific",
                "abbreviation": "lak",
                "mascot": "Kings",
                "color1": "#111111",
                "color2": "#A2AAAD",
                "color3": "#FFFFFF",
                "id": 24
            },
            "sjs": {
                "name": "San Jose Sharks",
                "home": "San Jose",
                "conference": "western",
                "division": "pacific",
                "abbreviation": "sjs",
                "mascot": "Sharks",
                "color1": "#006D75",
                "color2": "#000000",
                "color3": "#FFFFFF",
                "color4": "#006D75",
                "id": 25
            },
            "vgk": {
                "name": "Vegas Golden Knights",
                "home": "Vegas",
                "conference": "western",
                "division": "pacific",
                "abbreviation": "vgk",
                "mascot": "Golden Knights",
                "color1": "#B4975A",
                "color2": "#333F42",
                "color3": "#000000",
                "color4": "#C8102E",
                "color5": "#FFFFFF",
                "id": 26
            },
            "edm": {
                "name": "Edmonton Oilers",
                "home": "Oilers",
                "conference": "western",
                "division": "pacific",
                "abbreviation": "edm",
                "mascot": "Oilers",
                "color1": "#041E42",
                "color2": "#FF4C00",
                "color3": "",
                "id": 27
            },
            "cal": {
                "name": "Calgary Flames",
                "home": "Calgary",
                "conference": "western",
                "division": "pacific",
                "abbreviation": "cal",
                "mascot": "Flames",
                "color1": "#C8102E",
                "color2": "#F1BE48",
                "color3": "#111111",
                "color4": "#FFFFFF",
                "id": 28
            },
            "ari": {
                "name": "Arizona Coyotes",
                "home": "Arizona",
                "conference": "western",
                "division": "pacific",
                "abbreviation": "ari",
                "mascot": "Coyotes",
                "color1": "#8C2633",
                "color2": "#E2D6B5",
                "color3": "#111111",
                "id": 29
            },
            "van": {
                "name": "Vancouver Canucks",
                "home": "Vancouver",
                "conference": "western",
                "division": "pacific",
                "abbreviation": "van",
                "mascot": "Canucks",
                "color1": "#00205B",
                "color2": "#00843D",
                "color3": "#041C2C",
                "color4": "#99999A",
                "color5": "#FFFFFF",
                "id": 30
            },
            "ana": {
                "name": "Anaheim Ducks",
                "home": "Anaheim",
                "conference": "western",
                "division": "pacific",
                "abbreviation": "ana",
                "mascot": "Ducks",
                "color1": "#F47A38",
                "color2": "#B9975B",
                "color3": "#C1C6C8",
                "color4": "#000",
                "id": 31
            }
        }
    },
    "all-star": {
        "all-star": {
            "awa": {
                "name": "American All-Stars",
                "home": "American",
                "conference": "all-star",
                "division": "all-star",
                "abbreviation": "awa",
                "mascot": "All-Stars",
                "color1": "#0047ba",
                "color2": "white",
                "color3": "blue",
                "color4": "#000",
                "id": 7461
            },
            "cwa": {
                "name": "Canadian All-Stars",
                "home": "Canadian",
                "conference": "all-star",
                "division": "all-star",
                "abbreviation": "cwa",
                "mascot": "All-Stars",
                "color1": "#FFFFFF",
                "color2": "#B9975B",
                "color3": "#C1C6C8",
                "color4": "#000",
                "id": 7460
            },
            "atl": {
                "name": "Team Atlantic",
                "home": "Atlantic",
                "conference": "all-star",
                "division": "all-star",
                "abbreviation": "atl",
                "mascot": "Atlantic",
                "color1": "#F47A38",
                "color2": "#B9975B",
                "color3": "#C1C6C8",
                "color4": "#000",
                "id": 87
            },
            "met": {
                "name": "Team Metropolitan",
                "home": "Metropolitan",
                "conference": "all-star",
                "division": "all-star",
                "abbreviation": "met",
                "mascot": "Metropolitan",
                "color1": "#F47A38",
                "color2": "#B9975B",
                "color3": "#C1C6C8",
                "color4": "#000",
                "id": 88
            },
            "cen": {
                "name": "Team Central",
                "home": "Central",
                "conference": "all-star",
                "division": "all-star",
                "abbreviation": "cen",
                "mascot": "Central",
                "color1": "#F47A38",
                "color2": "#B9975B",
                "color3": "#C1C6C8",
                "color4": "#000",
                "id": 89
            },
            "pac": {
                "name": "Team Pacific",
                "home": "Pacific",
                "conference": "all-star",
                "division": "all-star",
                "abbreviation": "pac",
                "mascot": "Pacific",
                "color1": "#F47A38",
                "color2": "#B9975B",
                "color3": "#C1C6C8",
                "color4": "#000",
                "id": 90
            }
        }
    }
}

export default config
